### ISSUE TITLE
"typescript" could be a peer dependency

### ISSUE THREAD

**Issue by james-hu** [ts-oas/ts-oas#14]
This is just a suggestion. I just started trying using it and noticed that "typescript" is a dependency. Because most of the projects needing ts-oas should already have a version of "typescript" as its dev dependency, to avoid installing ts-oas affecting the effective version of "typescript" in the project, it would better to make "typescript" a peer dependency of "ts-oas". That also makes it easier for accurately stating compatibility, for example, you can have something like ">=4.9.0" instead of just "5.0.4".

**Comment by james-hu** [comment]
But I also see the benefit. By having "typescript" as a "normal" dependency, ts-oas always deals with the desired version of "typescript".

**Comment by alireza-mf** [comment]
Thank you for the suggestion. Although there’s an advantage when version is in a range, I’m concerned if even a minor version mismatch could cause issues as we're using very internal ts methods there. That's why I prefer to stick with locking it to a specific version, [similar to the package](https://github.com/YousefED/typescript-json-schema/blob/2422f97faab12e08a56cd643d04f6da6d86b8554/package.json#L50) that [inspired ours](https://github.com/ts-oas/ts-oas?tab=readme-ov-file#inspirations) which is a more tested and have a wider user base.

**Comment by james-hu** [comment]
What about "bundleDependencies" feature of NPM? 
I have not tested, but suppose if the consumer project has an existing dependency of typescript^5.0.0, after installing ts-oas, the effective typescript version would be silently upgraded to 5.0.4.

**Comment by alireza-mf** [comment]
if they have ^5.0.0 as dependencies, technically they assumed they're fine upgrading it to 5.0.4. 

[bundleDependencies](https://docs.npmjs.com/cli/v10/configuring-npm/package-json#bundledependencies) seems won't make things reusable I think:
> This defines an array of package names that will be bundled when publishing the package.
In cases where you need to preserve npm packages locally or have them available through a single file download, you can bundle the packages in a tarball file by specifying the package names in the bundleDependencies array and executing npm pack.

Anyway having it as a bit of a range like [this](https://github.com/YousefED/typescript-json-schema/blob/2422f97faab12e08a56cd643d04f6da6d86b8554/package.json#L50) is better, IMO.
